---

pdf:
  filename: Robert F.P. Ludwick Resume.pdf
  fonts:
    header: Times
    footer: Times
    default: Arial
  margins:
    left: 10
    top: 8
    right: 10
  keywords:
    - Ludwick
    - Resume
    - CV
    - Technology
    - Leadership
    - Software
flavor:
  header: Software Engineering Leader
  footer: "RFPL-Resume"
skills:
  first:
    title: "Management, Leadership, & Core Skills"
    count: 11
    tags:
      - non_technical
  second:
    title: "Technical Skills & Background"
    count: 11
    tags:
      - technical
  third:
    title: Additional Technical Skills
    count: 16
    tags:
      - technical
employers:
  expanded:
    title: Professional Experience
    count: 3
    bullet_points:
      start: 6
      decrement: 1
    collapse_multiple_positions: "titles-only"
    tags:
      - mainline
  condensed:
    title: Additional Professional Experience
    count: 3
    collapse_multiple_positions: collapse
    tags:
      - mainline
volunteering:
  expanded:
    count: 0
  condensed:
    count: 0
politics:
  expanded:
    count: 0
  condensed:
    count: 0
education:
  title: Education
  count: 2
certifications:
  title: Certifications
  count: 4
  tags:
    - mainline
projects:
  title: Projects
  count: 0
